### ISSUE TITLE
turn into pure html

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-date-icon#4]

**Comment by alexlemaire** [comment]
Done!

**Note:** right now the styles are written as a big `styles` getter inside of our element. This has to stay as is for now because `action-generate-docs` which is used to generate the documentation does not support retrieval of custom CSS properties at runtime. Therefore I am not able to replace the style block by multiple pure functions returning a `css` template string as the workflow would not be able to see the CSS custom properties anymore (being wrapped in the functions and only being evaluated at runtime).

I filed an issue for that [here](https://github.com/kaskadi/action-generate-docs/issues/33) to work on it later on.

Closing for now!
